### ISSUE TITLE
I can't launch PAL games

### ISSUE THREAD

**Issue by Vivesoad** [ericlewis/openFPGA-Genesis#27]
I have some problems with the genesis core on the analogue pocket, I can only play NTSC games, but when I try to launch PAL games I have this message. When I check the settings I don't see what's wrong, you can't manually change the region but Europe is automatically selected so I don't see what's happening.

![IMG_20230911_021955](https://github.com/opengateware/openFPGA-Genesis/assets/144670598/fc307208-76b6-4635-b234-7ec37344020f)

**Comment by lostb1t** [comment]
https://github.com/opengateware/openfpga-genesis#important-to-read-this-first

**Comment by Vivesoad** [comment]
Ok my bad thanks for the quick answer
