### ISSUE TITLE
audio filters are not correct

### ISSUE THREAD

**Issue by SegaSnatcher** [ericlewis/openFPGA-Genesis#4]
It appears there is a flaw in the implementation as Model 1 and Minimal filters appear to be the same filter and Model 2 and Unfiltered sound appear to be the same.

**Comment by ericlewis** [comment]
possibly fixed by https://github.com/ericlewis/openFPGA-Genesis/commit/5238742ca89dfc5ceb17edbba24390084fb4c95e

**Comment by SegaSnatcher** [comment]
Fixed in latest release.
