### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by Princepicklepants** [ericlewis/openFPGA-Genesis#9]
Not really an issue but I noticed on the about section in the core menu it’s missing your smiley face icon. Just think it’s a nice touch knowing who made each core with those icons. Great work by the way to everyone involved!

**Comment by ericlewis** [comment]
> Not really an issue but I noticed on the about section in the core menu it’s missing your smiley face icon. Just think it’s a nice touch knowing who made each core with those icons. Great work by the way to everyone involved!

That is actually the one that comes with! I need to make a "proper" icon.
